---
version: 2
jobs:
  build:
    docker:
      - image: rocker/r-base:latest
    steps:
      - checkout

      - run:
          name: "Installing bats"
          command: apt update && apt install -y bats

      - run:
          name: "Install binary R packages from Debian to skip compilation"
          command: |
              apt install -y r-cran-testthat r-cran-digest r-cran-jsonlite \
              r-cran-igraph r-cran-rstudioapi

      - run:
          name: "Installing lintr from CRAN"
          command: Rscript -e 'install.packages("lintr")'

      - run:
          name: "Running tests"
          command: pwd && ls -la && bats tests
