---
version: 2
jobs:
  build:
    docker:
      - image: rocker/r-base:latest
    steps:
      - checkout
      - run:
          name: "Installing lintr from CRAN"
          command: Rscript -e 'install.packages("lintr")'
      - run:
          name: "Installing bats"
          command: apt install -y bats
      - run:
        name: "Running tests"
        command: bats tests
