---
version: 2
jobs:
  build:
    docker:
      - image: rocker/r-base:latest
    steps:
      - checkout

      - run:
          name: "Installing bats"
          command: apt update && apt install -y bats

      - run:
          name: "Install binary R packages from Debian to skip compilation"
          command: |
              apt install -y libcurl4-openssl-dev libssl-dev

      - run:
          name: "Installing lintr from CRAN"
          command: Rscript -e 'install.packages("lintr")'

      - run:
          name: "Verifying that the lintr package can be loaded"
          command: Rscript -e 'require("lintr")'

      - run:
          name: "Running example"
          command: ./lintr example.R
      - run:
          name: "Running tests"
          command: bats tests
